name: Build and Deploy
on:
  push:
    branches:
      - main # 또는 master, 기본 브랜치에 따라 다름
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js 🔧
        uses: actions/setup-node@v3
        with:
          node-version: 16 # 사용하는 Node.js 버전

      - name: Install Dependencies 📦
        run: npm ci

      - name: Build 🏗️
        run: npm run build
        env:
          PUBLIC_URL: /talkingCard

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # 배포할 브랜치
          folder: build # 배포할 폴더
          clean: true # 기존 파일 자동 정리